import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { AppShell, Navbar, Header, Aside, Footer, createStyles} from '@mantine/core'
import { useState } from 'react'
import { FaComments } from 'react-icons/fa'

// from https://ui.mantine.dev/category/navbars

const useStyles = createStyles((theme, _params, getRef) => {
  const icon = getRef('icon')

  return {
      header: {
          paddingBottom: theme.spacing.lg,
          marginBottom: theme.spacing.md,
          borderBottom: `1px solid ${theme.colorScheme === 'dark' ? theme.colors.dark[4] : theme.colors.gray[2]}`
      },

      footer: {
          paddingBottom: theme.spacing.lg,
          marginBottom: theme.spacing.md,
          borderBottom: `1px solid ${theme.colorScheme === 'dark' ? theme.colors.dark[4] : theme.colors.gray[2]}`
      },


      link: {
          ...theme.fn.focusStyles(),
          display: 'flex',
          alignItems: 'center',
          textDecoration: 'none',
          fontSize: theme.fontSizes.sm,
          color: theme.colorScheme === 'dark' ? theme.colors.dark[1] : theme.colors.gray[7],
          padding: `${theme.spacing.xs}px ${theme.spacing.sm}px`,
          borderRadius: theme.radius.sm,
          fontWeight: 500,

          '&:hover': {
              backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[6] : theme.colors.gray[0],
              color: theme.colorScheme === 'dark' ? theme.white : theme.black,

              [`& .${icon}`]: {
                  color: theme.colorScheme === 'dark' ? theme.white : theme.black
              }
          }
      },

      linkIcon: {
          ref: icon,
          color: theme.colorScheme === 'dark' ? theme.colors.dark[2] : theme.colors.gray[6],
          marginRight: theme.spacing.sm
      },

      linkActive: {
          '&, &:hovoer': {
              backgroundColor: theme.fn.variant({ variant: 'light', color: theme.primaryColor }).background,
              color: theme.fn.variant({ variant: 'light', color: theme.primaryColor }).color,

              [`& .${icon}`]: {
                  color: theme.fn.variant({ variant: 'light', color: theme.primaryColor }).color
              }
          }
      }
  }
})


const navItems = [
  { link: '', label: 'Arguments', icon: FaComments}
]






const Home: NextPage = () => {


  const {classes, cx} = useStyles()
  const [active, setActive] = useState('Arguments')



  const links = navItems.map(item => (
    <a
        className={cx(classes.link, { [classes.linkActive]: item.label === active })}
        href={item.link}
        key={item.label}
        onClick={(event) => {
            event.preventDefault()
            setActive(item.label)
        }}
    >
        <item.icon className={classes.linkIcon} />
        <span>{item.label}</span>
    </a>
  ))


  return (
    <div className={styles.container}>
      <Head>
        <title>Pro-life Responses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* https://mantine.dev/core/app-shell/ */}
      {/* https://github.com/mantinedev/mantine/tree/master/src/mantine-demos/src/demos/core/AppShell */}
      <AppShell
        padding="md"
        navbar={<Navbar width={{ base: 300}} height={'100%'} p="xs">
          <Navbar.Section>
            {links}
          </Navbar.Section>
        </Navbar>}
        header={<Header height={60} p="xs">
          <h2 style={{margin: 0, marginLeft: '25px'}}>Pro-life Responses</h2>
        </Header>}
        styles={(theme) => ({
          main: { backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0] }
        })}
      >

      </AppShell>
    </div>
  )
}

export default Home
